main='dist/index.js'
compatibility_date = "2023-05-14"
name="cf-react"

kv_namespaces = [
    { binding = "__cf_react_site_assets", id = "db06acbfa07e452c929266cc5fda8313", preview_id = "07e1f6fd9bd74a5a855514f370714115" }
]

[vars]
__STATIC_CONTENT = "__cf_react_site_assets"

[build]
command = "yarn build"
watch_dir="src/"


