main = 'dist/index.js'
compatibility_date = "2023-05-11"
name = "beta-connorbray-net"
services = [{ binding = "connorbrayapi", service = "connorbrayapi" }]

[site]
bucket = "./public"

[build]
command = "yarn build"

[vars]
NODE_ENV = "production"

[env.production]
services = [{ binding = "connorbrayapi", service = "connorbrayapi" }]
routes = [{ pattern = "beta.connorbray.net", custom_domain = true }]

[env.production.vars]
NODE_ENV = "production"

[env.development]
services = [{ binding = "connorbrayapi", service = "connorbrayapi" }]
routes = [{ pattern = "dev.connorbray.net", custom_domain = true }]


[env.development.vars]
NODE_ENV = "development"

[env.development.build]
command = "yarn build"
watch_dir = "app/"
