main = 'dist/index.js'
compatibility_date = "2023-05-11"
name = "beta-connorbray-net"

[site]
bucket = "./public"

[build]
command = "yarn build"

[vars]
NODE_ENV = "production"

[env.production]
routes = [{pattern = "beta.connorbray.net", custom_domain = true}]

[env.production.vars]
NODE_ENV = "production"

[env.development]
routes = [{pattern = "dev.connorbray.net", custom_domain = true}]

[env.development.vars]
NODE_ENV = "development"

[env.development.build]
command = "yarn build:dev"
watch_dir = "app/"
